# Generated by Django 2.2.17 on 2021-01-11 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CarMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Марка авто')),
                ('image', models.ImageField(blank=True, upload_to='carmarks_images', verbose_name='Картинка марки')),
            ],
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Модель авто')),
                ('image', models.ImageField(blank=True, upload_to='carmodels_images', verbose_name='Картинка модели')),
            ],
        ),
        migrations.CreateModel(
            name='CarModifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, unique=True, verbose_name='Комплектация')),
                ('image', models.ImageField(blank=True, upload_to='carmod_images', verbose_name='Картинка модификации авто')),
            ],
        ),
        migrations.CreateModel(
            name='CarYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, unique=True, verbose_name='Год выпуска')),
                ('image', models.ImageField(blank=True, upload_to='caryear_images', verbose_name='Картинка авто определенного года')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64, unique=True, verbose_name='Название услуги')),
                ('image', models.ImageField(blank=True, upload_to='catalog_images', verbose_name='Картинка услуги')),
                ('short_desc', models.CharField(blank=True, max_length=60, verbose_name='Краткое описание услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogUnique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=64, verbose_name='Цена услуги')),
                ('decription', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('carinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CarInfo', verbose_name='ID авто')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Catalog', verbose_name='Выбранная услуга')),
            ],
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CarMarks', verbose_name='Марка авто'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CarModels', verbose_name='Модель авто'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CarModifications', verbose_name='Модификация(комплектация) авто'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CarYear', verbose_name='Год выпуска авто'),
        ),
    ]
