# Generated by Django 2.2.17 on 2021-01-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64, unique=True, verbose_name='Название услуги')),
                ('image', models.ImageField(blank=True, upload_to='category_images', verbose_name='Картинка услуги')),
                ('short_desc', models.CharField(blank=True, max_length=60, verbose_name='Краткое описание услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
            ],
        ),
    ]
