# Generated by Django 2.2.17 on 2021-04-19 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodels',
            name='car_mark',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.CarMarks', verbose_name='Марка авто'),
        ),
    ]
