# Generated by Django 2.2.17 on 2021-01-13 17:58

from django.db import migrations

def forwards_func(apps, schema_editor):
    car_marks_model = apps.get_model("mainapp", "CarMarks")
    car_models_model = apps.get_model("mainapp", "CarModels")
    car_years_model = apps.get_model("mainapp", "CarYear")
    car_modifications_model = apps.get_model("mainapp", "CarModifications")
    car_info_model = apps.get_model("mainapp", "CarInfo")
    car_catalog_model = apps.get_model("mainapp", "Catalog")
    car_catalogunique_model = apps.get_model("mainapp", "CatalogUnique")
    car_category_model = apps.get_model("mainapp", "Category")
    car_contact_model = apps.get_model("mainapp", "Contact")

    car_marks_obj = car_marks_model.objects.create(
        pk=1,
        name='Audi',
        # image=''
    )

    del car_marks_obj

    car_marks_obj = car_marks_model.objects.create(
        pk=2,
        name='Volkswagen',
        # image=''
    )

    del car_marks_obj

    car_marks_obj = car_marks_model.objects.create(
        pk=3,
        name='Skoda',
        # image=''
    )

    del car_marks_obj

    car_marks_obj = car_marks_model.objects.create(
        pk=4,
        name='Seat',
        # image=''
    )

    del car_marks_obj

    car_catalog_model.objects.create(
        pk=1,
        service_name="Замена масла",
        image="catalog_images/oil.jpg",
        short_desc="Замена масла ДВС",
        description="Меняем масло в двигателе или коробке передач",
    )
    car_catalog_model.objects.create(
        pk=2,
        service_name="Диагностика",
        image="catalog_images/diagnostics.jpg",
        short_desc="Компьютерная диагностика авто",
        description="Компьютерная диагностика авто всех блоков управления",
    )
    car_catalog_model.objects.create(
        pk=3,
        service_name="Ремонт двигателя",
        image="catalog_images/dvigatel.jpg",
        short_desc="Ремонтируем двигатель",
        description="Переборка/замена двигателя",
    )
    car_catalog_model.objects.create(
        pk=4,
        service_name="Ремонт КПП",
        image="catalog_images/dsg7_KPP.jpg",
        short_desc="Ремонтируем КПП",
        description="Ремонт/замена коробки передач/тюнинг",
    )
    car_catalog_model.objects.create(
        pk=5,
        service_name="Ремонт подвески",
        image="catalog_images/suspension.jpg",
        short_desc="Ремотируем подвеску",
        description="Замена неисправных элементов подвески",
    )
    car_catalog_model.objects.create(
        pk=6,
        service_name="Шиномонтаж",
        image="catalog_images/tires.jpg",
        short_desc="шиномонтаж",
        description="Замена колес/балансировка колес/подкачка шин и тд.",
    )

    car_category_model.objects.create(
        pk=1,
        category_name="Замена масла",
        image="category_images/oil.jpg",
        short_desc="Замена масла ДВС",
        description="Меняем масло в двигателе или коробке передач",
    )
    car_category_model.objects.create(
        pk=2,
        category_name="Диагностика",
        image="category_images/diagnostics.jpg",
        short_desc="Компьютерная диагностика авто",
        description="Компьютерная диагностика авто всех блоков управления",
    )
    car_category_model.objects.create(
        pk=3,
        category_name="Ремонт двигателя",
        image="category_images/dvigatel.jpg",
        short_desc="Ремонтируем двигатель",
        description="Переборка/замена двигателя",
    )
    car_category_model.objects.create(
        pk=4,
        category_name="Шиномонтаж",
        image="catalog_images/tires.jpg",
        short_desc="шиномонтаж",
        description="Замена колес/балансировка колес/подкачка шин и тд.",
    )
    car_category_model.objects.create(
        pk=5,
        category_name="Ремонт подвески",
        image="category_images/suspension.jpg",
        short_desc="Ремотируем подвеску",
        description="Замена неисправных элементов подвески",
    )

    car_contact_model.objects.create(
        pk=1,
        phone="+7-888-888-8888",
        email="info@geekshop.ru",
        city="Москва",
        address="В пределах МКАД",
    )

def reverse_func(apps, schema_editor):
    car_marks_model = apps.get_model("mainapp", "CarMarks")
    car_models_model = apps.get_model("mainapp", "CarModels")
    car_years_model = apps.get_model("mainapp", "CarYear")
    car_modifications_model = apps.get_model("mainapp", "CarModifications")
    car_catalog_model = apps.get_model("mainapp", "Catalog")
    car_category_model = apps.get_model("mainapp", "Category")
    car_contact_model = apps.get_model("mainapp", "Contact")

    car_marks_model.objects.all().delete()
    car_models_model.objects.all().delete()
    car_years_model.objects.all().delete()
    car_modifications_model.objects.all().delete()
    car_catalog_model.objects.all().delete()
    car_category_model.objects.all().delete()
    car_contact_model.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_contact'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
